# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Go3mf < Formula
  desc "Command-line tool for consuming Kafka topics"
  homepage "https://github.com/philipparndt/go3mf"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philipparndt/go3mf/releases/download/v0.4.0/go3mf_darwin_x86_64.tar.gz"
      sha256 "5068a5cbceebeb9e6412194c0b864cebd894dea3f936f86ff4bc55d7efd6b3a4"

      def install
        bin.install "go3mf"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/go3mf completion bash")
          (bash_completion/"go3mf").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/go3mf completion zsh")
          (zsh_completion/"_go3mf").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/go3mf completion fish")
          (fish_completion/"go3mf.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philipparndt/go3mf/releases/download/v0.4.0/go3mf_darwin_arm64.tar.gz"
      sha256 "2b1aa54d0ef22f981946995ccdc708f5aa66cd923a00e81e713a562d8be85966"

      def install
        bin.install "go3mf"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/go3mf completion bash")
          (bash_completion/"go3mf").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/go3mf completion zsh")
          (zsh_completion/"_go3mf").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/go3mf completion fish")
          (fish_completion/"go3mf.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/go3mf/releases/download/v0.4.0/go3mf_linux_x86_64.tar.gz"
      sha256 "83b09eba247e8fbd01d1b8a266c6ffe1212745ba8120ddbbc88dd26602a1c6d4"
      def install
        bin.install "go3mf"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/go3mf completion bash")
          (bash_completion/"go3mf").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/go3mf completion zsh")
          (zsh_completion/"_go3mf").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/go3mf completion fish")
          (fish_completion/"go3mf.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/go3mf/releases/download/v0.4.0/go3mf_linux_arm64.tar.gz"
      sha256 "5c3180f491b0d628ac9cd04b6009fecd7dcbd6330718fb7201593e026234e2d4"
      def install
        bin.install "go3mf"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/go3mf completion bash")
          (bash_completion/"go3mf").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/go3mf completion zsh")
          (zsh_completion/"_go3mf").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/go3mf completion fish")
          (fish_completion/"go3mf.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run using go3mf.
    EOS
  end
end
